# Generated by Django 5.2.10 on 2026-02-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_box_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_box_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
