# Generated by Django 5.2.10 on 2026-02-11 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='opened_by',
            field=models.ManyToManyField(blank=True, related_name='opened_boxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
